FROM centos/python-36-centos7:latest

USER root

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts
    
COPY /tmp/src/jupyterhub-80.png /opt/app-root/share/jupyterhub/static/images/jupyterhub-80.png
COPY /tmp/src/jupyter.png /opt/app-root/share/jupyterhub/static/images/jupyter.png

USER 1001

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
