FROM centos/python-35-centos7:latest

USER root

COPY . /tmp/src

RUN rm -rf /tmp/src/.git* && \
    chown -R 1001 /tmp/src && \
    chgrp -R 0 /tmp/src && \
    chmod -R g+w /tmp/src && \
    rm -rf /tmp/scripts && \
    mv /tmp/src/.s2i/bin /tmp/scripts
RUN yum -y update 
RUN yum -y install curl bzip2 
RUN curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh 
RUN bash /tmp/miniconda.sh -bfp /usr/local/ 
RUN rm -rf /tmp/miniconda.sh 
RUN conda install -y python=3 
RUN conda update conda --yes
RUN conda clean --all --yes 
RUN rpm -e --nodeps curl bzip2 
RUN yum clean all

USER 1001

RUN /tmp/scripts/assemble

CMD [ "/opt/app-root/builder/run" ]
